development:
  adapter: postgresql
  database: ctgs
  username: ctgsuser
  password: 1234
  host: localhost
  port: 5432

test:
  adapter: postgresql
  database: ctgs
  username: ctgsuser
  password: 1234
  host: localhost

production:
  adapter: postgresql
  database: ctgs
  username: ctgsuser
  password: 1234
  host: localhost
  port: 5432